/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pboagungs;

import pboagungs.models.DataPassword;

public class App {

    public static void main(String[] args) {
        try {
            new MainPage("Main Page", 50).draw();
            // DataPassword.loadCSVData();
            // DataPassword.saveCSVData();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
